import type { Metadata } from "next";
import airlines from "../data/airlines.json";
import "./globals.scss";
import O1Information from "./components/organisms/o1-information/o1-information";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

airlines.airlines.forEach((name: any) => {
  console.log(name);
});

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <main></main>
      </body>
    </html>
  );
}
